# Generated by Django 3.2.9 on 2021-11-19 18:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods_api', '0003_auto_20211119_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='linked_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
